---
- name: Installer Apache
  apt:
    name: apache2
    state: present
  when: ansible_facts['os_family'] == 'ubuntu18.04'

- name: lancer apache2
  service:
    name: apache2
    state: started
  register: apache

- name: Lancer la vérifiaction d'apache
  debug:
    msg: "{{apache.status}}"
...
