---
- name: Creation Utilisateur
  hosts: webserver
  remote_user: root
  vars_files:
    - "vars/{{env}}_secret.yml"
    - "vars/{{env}}_secret.yml"
  roles:
    - { role: create_user }
    - { role: vim_install }
    - { role: apache_install}
