---
- hosts: webserver
  remote_user: root
  vars_files:
          - "vars/{{env}}_vars.yml"
  tasks:
   - name: debug
     debug:
       msg: "bonjour, ici {{env}}"

   - name: vim install/unistall
     apt:
        name: vim
        state: "{{vim_state}}"
